language: ruby

rvm:
  - 1.9.3

env:
  - PAGEFLOW_RAILS_VERSION=4.0.4
  - PAGEFLOW_RAILS_VERSION=4.1.6

services:
  - redis-server

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - exec/rspec
  - exec/teaspoon
